


services:
  web:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - .:/app   # Mount the entire project directory
      - ./dev_test_data:/dev_test_data  # Map dev_test_data directly to /dev_test_data in the container
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=lac_fullstack_dev
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=your_secret_key
    depends_on:
      - db


  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: lac_fullstack_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dev_test_data:/dev_test_data

volumes:
  db_data: